### PR TITLE
Working react move

### LINKED ISSUE #25: Move to a github workflow design
The goal is to make a github workflow that operates the website. I am not certain how this will work but i will look into it.

### LINKED ISSUE #28: made a exact clone of "under construction" website in next.js
took a while but it needs refinement

### PR DESCRIPTION
**Pull request by Negative-light**
The goal of this is to move the current application to a Next.js website.
This will close #28 and #25.

This was a larger undertaking than anticipated but overall should allow us to create a more dynamic website overall.

### CODE REVIEW

**Review by Negative-light — COMMENTED** [review]
These changes are all good and the website does populate. Others can approve it or i will manually merge myself later in the week.

**Review by crazysmile11012 — CHANGES_REQUESTED** [review]
have some tweaks before final

**Comment by Negative-light** [comment]
Changes were made by Crazy smile & Negative_light therefore we will bypass the review. We have reviewed each other's work.

**Comment by crazysmile11012** [comment]
im makin some tweaks

**Comment by Negative-light** [comment]
oh, ok lmk when you have finised with the changes

**Pull request merged**
