### PR TITLE
updated index.html

### PR DESCRIPTION
**Pull request by crazysmile11012**
made the under construction page look professional with css instead of plain old html

### CODE REVIEW

**Comment by crazysmile11012** [comment]
image_2023-08-25_104642961

**Comment by Negative-light** [comment]
This looks good could end up replacing thr linktrree lol

**Comment by crazysmile11012** [comment]
il do that and request round two of the review gantlet

**Comment by crazysmile11012** [comment]
this should be of satisfactory quality

**Comment by crazysmile11012** [comment]
image_2023-08-25_105325578

**Comment by crazysmile11012** [comment]
the buttons also have fancy hover effect =)

**Review by Negative-light — APPROVED** [review]
Overall this looks better than it was.
In the future lets branch off of Dev rather than main

**Pull request merged**
