### PR TITLE
changed interface.

### LINKED ISSUE #6: style and layout of webpage
i have a few ideas for layouts & styles that need enhancement and feedback before we advance

### PR DESCRIPTION
**Pull request by sourabhsharma24**
resolve #6 .

### CODE REVIEW

**Comment by Negative-light** [comment]
I like what you did thank you sourabh. I will be reviewing everything shortly

**Comment by Negative-light** [comment]
We will need to merge in some changes but I love what you did. Thank you so much. I think I can merge this change set and we will work on our other changes.
We also just added our contributing file. You can find it in the development branch.

**Comment by Negative-light** [comment]
Ok I have a merge setup going to push it up to development and merge from there if needed.

**Review by Negative-light — APPROVED** [review]
This looks good. I had to do a merge myself, so there may be issues.
I think we can make the process smoother in the future by
1. Looking into Merge QUeues
2. Requiring pushes to manage their own merge conflicts

**Comment by sourabhsharma24** [comment]
Thanks Negative-light , for your kind appreciation. I'm glad to help you out today .it's great, that it was helpful and a lots of wishes to you 👍.

**Pull request merged**
